/*
 * ConfigureButtonsSample.java
 *
 * Created on 15. September 2006, 00:14
 */

package samples.swing.action;

import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JToolBar;
import javax.swing.SwingUtilities;
import org.apache.xpath.axes.LocPathIterator;
import org.softsmithy.lib.swing.action.AbstractXAction;
import org.softsmithy.lib.swing.action.DevelopmentActionFactory;
import org.softsmithy.lib.swing.action.GeneralActionFactory;
import org.softsmithy.lib.swing.action.IconType;
import org.softsmithy.lib.swing.action.MediaActionFactory;
import org.softsmithy.lib.swing.action.NavigationActionFactory;
import org.softsmithy.lib.swing.action.StandardActionFactory;
import org.softsmithy.lib.swing.action.TableActionFactory;
import org.softsmithy.lib.swing.action.TextActionFactory;
import org.softsmithy.lib.swing.action.XAction;
import org.softsmithy.lib.swing.action.XActions;

/**
 *
 * @author  puce
 */
public class StandardActionFactoriesSample extends javax.swing.JFrame {
    
    /** Creates new form ConfigureButtonsSample */
    public StandardActionFactoriesSample() {
        initComponents();
        XAction[] developmentActions = createDevelopmentActions();
        XAction[] generalActions = createGeneralActions();
        XAction[] mediaActions = createMediaActions();
        XAction[] navigationActions = createNavigationActions();
        XAction[] tableActions = createTableActions();
        XAction[] textActions = createTextActions();
        addMenuItems(developmentActions, developmentMenu);
        addMenuItems(generalActions, generalMenu);
        addMenuItems(mediaActions, mediaMenu);
        addMenuItems(navigationActions, navigationMenu);
        addMenuItems(tableActions, tableMenu);
        addMenuItems(textActions, textMenu);
        addToolbarButtons(developmentActions, developmentToolBar);
        List generalActionsList = Arrays.asList(generalActions);
        addToolbarButtons((XAction[])generalActionsList.subList(0,23).toArray(new XAction[23]), generalToolBar1);
        addToolbarButtons((XAction[])generalActionsList.subList(23,generalActionsList.size()).toArray(new XAction[generalActionsList.size()-23]), generalToolBar2);
        addToolbarButtons(mediaActions, mediaToolBar);
        addToolbarButtons(navigationActions, navigationToolBar);
        addToolbarButtons(tableActions, tableToolBar);
        addToolbarButtons(textActions, textToolBar);
        setSize(1050, 500);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        developmentToolBar = new javax.swing.JToolBar();
        generalToolBar1 = new javax.swing.JToolBar();
        generalToolBar2 = new javax.swing.JToolBar();
        mediaToolBar = new javax.swing.JToolBar();
        navigationToolBar = new javax.swing.JToolBar();
        tableToolBar = new javax.swing.JToolBar();
        textToolBar = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        developmentMenu = new javax.swing.JMenu();
        generalMenu = new javax.swing.JMenu();
        mediaMenu = new javax.swing.JMenu();
        navigationMenu = new javax.swing.JMenu();
        tableMenu = new javax.swing.JMenu();
        textMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Standard Action Factories Sample");
        jPanel1.setLayout(new java.awt.GridLayout(7, 1));

        jPanel1.add(developmentToolBar);

        jPanel1.add(generalToolBar1);

        jPanel1.add(generalToolBar2);

        jPanel1.add(mediaToolBar);

        jPanel1.add(navigationToolBar);

        jPanel1.add(tableToolBar);

        jPanel1.add(textToolBar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        developmentMenu.setText("Development");
        jMenuBar1.add(developmentMenu);

        generalMenu.setText("General");
        jMenuBar1.add(generalMenu);

        mediaMenu.setText("Media");
        jMenuBar1.add(mediaMenu);

        navigationMenu.setText("Navigation");
        jMenuBar1.add(navigationMenu);

        tableMenu.setText("Table");
        jMenuBar1.add(tableMenu);

        textMenu.setText("Text");
        jMenuBar1.add(textMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Locale.setDefault(Locale.ENGLISH);
        JComponent.setDefaultLocale(Locale.getDefault());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StandardActionFactoriesSample().setVisible(true);
            }
        });
        
    }
    
    private void addMenuItems(XAction[] xActions, JMenu menu) {
        for (int i=0; i < xActions.length; i++){
            JMenuItem item = XActions.createMenuItem(xActions[i], IconType.SMALL_ICON, true);
            menu.add(item);
        }
    }
    
    private void addToolbarButtons(XAction[] xActions, JToolBar toolBar) {
        for (int i=0; i < xActions.length; i++){
            JButton button = XActions.createButton(xActions[i], IconType.LARGE_ICON, false, true);
            toolBar.add(button);
        }
    }
   
    
    
    private XAction[] createActions(StandardActionFactory[] factories) {
        XAction[] xActions = new XAction[factories.length];
        for (int i=0; i<factories.length; i++){
            StandardActionFactory factory = factories[i];
            XAction xAction = new AbstractXAction(){
                public void actionPerformed(ActionEvent e) {
                    JOptionPane.showMessageDialog(StandardActionFactoriesSample.this,
                            "Action performed: " + getName(), "Action Performed!", JOptionPane.INFORMATION_MESSAGE);
                }
            };
            factory.configureXAction(xAction, Locale.getDefault());
            xActions[i] = xAction;
        }
        return xActions;
    }
    
    
    private XAction[] createDevelopmentActions() {
        DevelopmentActionFactory[] factories = {
            DevelopmentActionFactory.APPLET,
            DevelopmentActionFactory.APPLICATION,
            DevelopmentActionFactory.APPLICATION_DEPLOY,
            DevelopmentActionFactory.BEAN,
            DevelopmentActionFactory.BEAN_ADD,
            DevelopmentActionFactory.ENTERPRISE_JAVA_BEAN,
            DevelopmentActionFactory.ENTERPRISE_JAVA_BEAN_JAR,
            DevelopmentActionFactory.HOST,
            DevelopmentActionFactory.J2EE_APPLICATION,
            DevelopmentActionFactory.J2EE_APPLICATION_CLIENT,
            DevelopmentActionFactory.J2EE_APPLICATION_CLIENT_ADD,
            DevelopmentActionFactory.J2EE_SERVER,
            DevelopmentActionFactory.JAR,
            DevelopmentActionFactory.JAR_ADD,
            DevelopmentActionFactory.SERVER,
            DevelopmentActionFactory.WAR,
            DevelopmentActionFactory.WAR_ADD,
            DevelopmentActionFactory.WEB_COMPONENT,
            DevelopmentActionFactory.WEB_COMPONENT_ADD};
        return createActions(factories);
    }
    
    private XAction[] createGeneralActions() {
        GeneralActionFactory[] factories = {
            GeneralActionFactory.ABOUT,
            GeneralActionFactory.ADD,
            GeneralActionFactory.ALIGN_BOTTOM,
            GeneralActionFactory.ALIGN_CENTER,
            GeneralActionFactory.ALIGN_JUSTIFY_HORIZONTAL,
            GeneralActionFactory.ALIGN_JUSTIFY_VERTICAL,
            GeneralActionFactory.ALIGN_LEFT,
            GeneralActionFactory.ALIGN_RIGHT,
            GeneralActionFactory.ALIGN_TOP,
            GeneralActionFactory.BOOKMARKS,
            GeneralActionFactory.COMPOSE_MAIL,
            GeneralActionFactory.CONTEXTUAL_HELP,
            GeneralActionFactory.COPY,
            GeneralActionFactory.CUT,
            GeneralActionFactory.DELETE,
            GeneralActionFactory.EDIT,
            GeneralActionFactory.EXPORT,
            GeneralActionFactory.FIND,
            GeneralActionFactory.FIND_AGAIN,
            GeneralActionFactory.HELP,
            GeneralActionFactory.HISTORY,
            GeneralActionFactory.IMPORT,
            GeneralActionFactory.INFORMATION,
            GeneralActionFactory.NEW,
            GeneralActionFactory.OPEN,
            GeneralActionFactory.PAGE_SETUP,
            GeneralActionFactory.PASTE,
            GeneralActionFactory.PREFERENCES,
            GeneralActionFactory.PRINT,
            GeneralActionFactory.PRINT_PREVIEW,
            GeneralActionFactory.PROPERTIES,
            GeneralActionFactory.REDO,
            GeneralActionFactory.REFRESH,
            GeneralActionFactory.REMOVE,
            GeneralActionFactory.REPLACE,
            GeneralActionFactory.SAVE,
            GeneralActionFactory.SAVE_ALL,
            GeneralActionFactory.SAVE_AS,
            GeneralActionFactory.SEARCH,
            GeneralActionFactory.SEND_MAIL,
            GeneralActionFactory.STOP,
            GeneralActionFactory.TIP_OF_THE_DAY,
            GeneralActionFactory.UNDO,
            GeneralActionFactory.ZOOM,
            GeneralActionFactory.ZOOM_IN,
            GeneralActionFactory.ZOOM_OUT};
        return createActions(factories);
    }
    
    private XAction[] createMediaActions() {
        MediaActionFactory[] factories = {
            MediaActionFactory.FAST_FORWARD,
            MediaActionFactory.MOVIE,
            MediaActionFactory.PAUSE,
            MediaActionFactory.PLAY,
            MediaActionFactory.REWIND,
            MediaActionFactory.STEP_BACK,
            MediaActionFactory.STEP_FORWARD,
            MediaActionFactory.STOP,
            MediaActionFactory.VOLUME};
        return createActions(factories);
    }
    
    private XAction[] createNavigationActions() {
         NavigationActionFactory[] factories = {
             NavigationActionFactory.BACK,
             NavigationActionFactory.DOWN,
             NavigationActionFactory.FORWARD,
             NavigationActionFactory.HOME,
             NavigationActionFactory.UP};
        return createActions(factories);
    }
    
    private XAction[] createTableActions() {
        TableActionFactory[] factories = {
            TableActionFactory.COLUMN_DELETE,
            TableActionFactory.COLUMN_INSERT_AFTER,
            TableActionFactory.COLUMN_INSERT_BEFORE,
            TableActionFactory.ROW_DELETE,
            TableActionFactory.ROW_INSERT_AFTER,
            TableActionFactory.ROW_INSERT_BEFORE};
        return createActions(factories);
    }

    private XAction[] createTextActions() {
        TextActionFactory[] factories = {
            TextActionFactory.ALIGN_CENTER,
            TextActionFactory.ALIGN_JUSTIFY,
            TextActionFactory.ALIGN_LEFT,
            TextActionFactory.ALIGN_RIGHT,
            TextActionFactory.BOLD,
            TextActionFactory.ITALIC,
            TextActionFactory.NORMAL,
            TextActionFactory.UNDERLINE};
       return createActions(factories);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu developmentMenu;
    private javax.swing.JToolBar developmentToolBar;
    private javax.swing.JMenu generalMenu;
    private javax.swing.JToolBar generalToolBar1;
    private javax.swing.JToolBar generalToolBar2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mediaMenu;
    private javax.swing.JToolBar mediaToolBar;
    private javax.swing.JMenu navigationMenu;
    private javax.swing.JToolBar navigationToolBar;
    private javax.swing.JMenu tableMenu;
    private javax.swing.JToolBar tableToolBar;
    private javax.swing.JMenu textMenu;
    private javax.swing.JToolBar textToolBar;
    // End of variables declaration//GEN-END:variables
    

}
