
/*
 * VepFrame2.java
 *
 * Created on 18. Juni 2006, 23:23
 */

package org.softsmithy.vep;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Locale;
import javax.swing.JColorChooser;
import org.softsmithy.lib.swing.action.IconType;
import org.softsmithy.lib.swing.action.MediaActionFactory;
import org.softsmithy.lib.swing.action.XAction;
import org.softsmithy.lib.swing.action.XActions;

/**
 *
 * @author  florian.brunner
 */
public class VepFrame extends javax.swing.JFrame {
    
    private final  VisualFieldPane visualFieldPane;
    /** Creates new form VepFrame2 */
    public VepFrame() {
        initComponents();
        visualFieldPane = new VisualFieldPane();
        try {
            XAction start = MediaActionFactory.PLAY.createXAction(this, Locale.getDefault());
            start.setShortDescription("Start");
            XActions.configureButton(startButton, start, IconType.LARGE_ICON, false, false);
            XAction stop = MediaActionFactory.STOP.createXAction(this, Locale.getDefault());
            stop.setEnabled(false);
            XActions.configureButton(stopButton, stop, IconType.LARGE_ICON, false, false);
        } catch (NoSuchMethodException ex) {
            ex.printStackTrace();
        }
        jSplitPane1.setLeftComponent(visualFieldPane);
        visualFieldPane.setVisualFieldTest((VisualFieldTest) visualFieldTestBox.getSelectedItem());
        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
        firstColorLabel.setBackground(visualFieldPane.getPrimaryColor());
        secondColorLabel.setBackground(visualFieldPane.getSecondaryColor());
    }
    
    public void mediaPlay(ActionEvent e){
        visualFieldPane.start();
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
    }
    
    public void mediaStop(ActionEvent e){
        visualFieldPane.stop();
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        visualFieldTestBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        frequencyBox = new javax.swing.JComboBox();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        firstColorCaptionLabel = new javax.swing.JLabel();
        secondColorCaptionLabel = new javax.swing.JLabel();
        firstColorLabel = new javax.swing.JLabel();
        secondColorLabel = new javax.swing.JLabel();
        firstColorButton = new javax.swing.JButton();
        secondColorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visually Evoked Potentials");
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setOneTouchExpandable(true);
        jLabel1.setLabelFor(visualFieldTestBox);
        jLabel1.setText("Visual Field Test: ");

        visualFieldTestBox.setModel(new javax.swing.DefaultComboBoxModel(VisualFieldTest.values()));
        visualFieldTestBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualFieldTestBoxActionPerformed(evt);
            }
        });

        jLabel2.setLabelFor(frequencyBox);
        jLabel2.setText("Frequency [Hz]: ");

        frequencyBox.setModel(new javax.swing.DefaultComboBoxModel(new Integer[]{2, 4, 8, 16}));
        frequencyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyBoxActionPerformed(evt);
            }
        });

        stopButton.setEnabled(false);

        firstColorCaptionLabel.setText("First Color: ");

        secondColorCaptionLabel.setText("Second Color: ");

        firstColorLabel.setOpaque(true);

        secondColorLabel.setOpaque(true);

        firstColorButton.setText("...");
        firstColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstColorButtonActionPerformed(evt);
            }
        });

        secondColorButton.setText("...");
        secondColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondColorButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(secondColorCaptionLabel)
                    .add(firstColorCaptionLabel)
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(frequencyBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(visualFieldTestBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(secondColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(secondColorButton))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(firstColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(16, 16, 16)
                                .add(firstColorButton)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(visualFieldTestBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(16, 16, 16)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(frequencyBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(firstColorCaptionLabel)
                    .add(firstColorButton)
                    .add(firstColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(secondColorCaptionLabel)
                    .add(secondColorButton)
                    .add(secondColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(108, 108, 108))
        );
        jSplitPane1.setRightComponent(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secondColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getSecondaryColor());
        if (color != null){
            secondColorLabel.setBackground(color);
            visualFieldPane.setSecondaryColor(color);
        }
    }//GEN-LAST:event_secondColorButtonActionPerformed
        
    private void firstColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getPrimaryColor());
        if (color != null){
            firstColorLabel.setBackground(color);
            visualFieldPane.setPrimaryColor(color);
        }
    }//GEN-LAST:event_firstColorButtonActionPerformed
    
    private void frequencyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyBoxActionPerformed
        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
    }//GEN-LAST:event_frequencyBoxActionPerformed
    
    private void visualFieldTestBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualFieldTestBoxActionPerformed
        visualFieldPane.setVisualFieldTest((VisualFieldTest) visualFieldTestBox.getSelectedItem());
    }//GEN-LAST:event_visualFieldTestBoxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VepFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstColorButton;
    private javax.swing.JLabel firstColorCaptionLabel;
    private javax.swing.JLabel firstColorLabel;
    private javax.swing.JComboBox frequencyBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton secondColorButton;
    private javax.swing.JLabel secondColorCaptionLabel;
    private javax.swing.JLabel secondColorLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox visualFieldTestBox;
    // End of variables declaration//GEN-END:variables
    
}
