/*
 *                  Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is SoftSmithy Utility Library. The Initial Developer of the
 * Original Code is Florian Brunner (Sourceforge.net user: puce). All Rights Reserved.
 *
 * Contributor(s): .
 */

package samples.swing.component;

/**
 *
 * @author  puce
 */
public class FileRootSelectionSample extends javax.swing.JFrame {

    /** Creates new form LocaleSelectionSample */
    public FileRootSelectionSample() {
        initComponents();

        setSize(350, 250);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileRootComboBox = new org.softsmithy.lib.swing.JFileRootComboBox();
        fileRootScrollPane = new javax.swing.JScrollPane();
        fileRootList = new org.softsmithy.lib.swing.JFileRootList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fileRootComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileRootComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(fileRootComboBox, gridBagConstraints);

        fileRootList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fileRootListValueChanged(evt);
            }
        });
        fileRootScrollPane.setViewportView(fileRootList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(fileRootScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void fileRootComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileRootComboBoxActionPerformed
    fileRootList.setSelectedValue(fileRootComboBox.getSelectedItem(), true);
}//GEN-LAST:event_fileRootComboBoxActionPerformed

private void fileRootListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fileRootListValueChanged
    if (!evt.getValueIsAdjusting()) {
        fileRootComboBox.setSelectedItem(fileRootList.getSelectedValue());
    }
}//GEN-LAST:event_fileRootListValueChanged
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FileRootSelectionSample().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.softsmithy.lib.swing.JFileRootComboBox fileRootComboBox;
    private org.softsmithy.lib.swing.JFileRootList fileRootList;
    private javax.swing.JScrollPane fileRootScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
