/*
 * SimpleSingleCustomizerSample.java
 *
 * Created on 29. Juni 2006, 20:29
 */

package samples.swing.customizer;

/**
 *
 * @author  florian.brunner
 */
public class SimpleSingleCustomizerSample extends javax.swing.JFrame {
    
    /** Creates new form SimpleSingleCustomizerSample */
    public SimpleSingleCustomizerSample() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jCustomizerPane1 = new org.softsmithy.lib.swing.JCustomizerPane();

        getContentPane().setLayout(new java.awt.GridLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A Simple Single Customizer Sample");

        getContentPane().add(jCustomizerPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleSingleCustomizerSample().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.softsmithy.lib.swing.JCustomizerPane jCustomizerPane1;
    // End of variables declaration//GEN-END:variables
    
}
