/*
 * CustomizerBarTabPane.java
 *
 * Created on 12. September 2002, 12:19
 */

package puce.swing;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import puce.swing.*;

/**
 *
 * @author  puce
 */
public abstract class JTableCustomizerBar extends JPanel implements CustomizerBar{
  
  /** Creates new form CustomizerBarTabPane */
  public JTableCustomizerBar(TableModel tm) {
    initComponents();
    table = new JTable(tm);
    table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    scrollPane = new JScrollPane(table);
    add(BorderLayout.CENTER, scrollPane);
    table.setShowGrid(false);
  }
  
  /** Creates new form CustomizerBarTabPane */
  public JTableCustomizerBar(TableModel tm, int rowHeight) {
    this(tm);
    table.setRowHeight(rowHeight+table.getRowMargin());
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents

    setLayout(new java.awt.BorderLayout());

  }//GEN-END:initComponents
  
  public void clearSelection() {
    table.clearSelection();
  }
  
  public boolean hasSelection() {
    return table.getSelectedRowCount() > 0;
  }
  
  public int getSelection() {
    return table.getSelectedRow();
  }
  
  public TableModel getTableModel(){
    return table.getModel();
  }
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
  private JTable table;
  
  private JScrollPane scrollPane;
  
}
