/*
 * JTreeCustomizerBar.java
 *
 * Created on 27. Februar 2003, 19:20
 */

package org.softsmithy.lib.swing;

import java.awt.*;
import javax.swing.*;
import javax.swing.tree.*;

/**
 *
 * @author  puce
 */
public abstract class JTreeCustomizerBar extends JPanel implements CustomizerBar {
  
  private JTree tree;
  
  /** Creates new form JTreeCustomizerBar */
  public JTreeCustomizerBar(TreeModel tm) {
    this(new JTree(tm));
  }
  
  public JTreeCustomizerBar(JTree tree) {
    initComponents();
    this.tree = tree;
    tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
    JScrollPane scrollPane = new JScrollPane(tree);
    add(scrollPane, BorderLayout.CENTER);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents

    setLayout(new java.awt.BorderLayout());

  }//GEN-END:initComponents
  
  public void clearSelection() {
    tree.clearSelection();
  }
  
  public TreePath getSelectionPath(){
    return tree.getSelectionPath();
  }
  
  public Object getSelectedNode(){
    Object node = null;
    if (tree.getSelectionPath() != null){
      node = tree.getSelectionPath().getLastPathComponent();
    }
    return node;
  }
  
  public boolean hasSelection() {
    return ! tree.isSelectionEmpty();
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
