/*
 *                  Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is SoftSmithy Utility Library. The Initial Developer of the
 * Original Code is Florian Brunner (Sourceforge.net user: puce). All Rights Reserved.
 *
 * Contributor(s): .
 */

/*
 * JXApplet.java
 *
 * Created on 30. Oktober 2002, 11:14
 */

package org.softsmithy.lib.swing;

import java.util.*;

/**
 *
 * @author  puce
 */
public class JXApplet extends javax.swing.JApplet {
  
  private String documentBaseDir = null;
  
  /** Creates new form JXApplet */
  public JXApplet() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    
  }//GEN-END:initComponents
  
  /**
   * Returns the string representation of the absolute URL naming the directory of the document in which
   * the applet is embedded. For example, suppose an applet is contained within the document:
   * http://java.sun.com/products/jdk/1.2/index.html
   *
   * The document base directory is:
   * http://java.sun.com/products/jdk/1.2/
   *
   * Note: Needed due to the bug <a href="http://developer.java.sun.com/developer/bugParade/bugs/4710854.html">
   * 4710854</a>
   */
  public String getDocumentBaseDir(){
    if (documentBaseDir == null){
      documentBaseDir = getDocumentBase().toString().replaceFirst("/[^/]*$", "") + "/";
    }
    return documentBaseDir;
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
