/*
 *                  Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is Examples of SoftSmithy Utility Library. The Initial Developer of the
 * Original Code is Florian Brunner (Sourceforge.net user: puce). All Rights Reserved.
 *
 * Contributor(s): .
 */

/*
 * Example1.java
 *
 * Created on 9. März 2003, 18:23
 */

package examples.swing.customizer;

import javax.swing.*;
import org.softsmithy.lib.awt.layout.*;
import org.softsmithy.lib.swing.*;

/**
 *
 * @author  puce
 */
public class SimpleExampleApplet extends JApplet {
  
  /** Creates new form Example1 */
  public SimpleExampleApplet() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents

  }//GEN-END:initComponents
  
  /** Called by the browser or applet viewer to inform
   * this applet that it has been loaded into the system. It is always
   * called before the first time that the <code>start</code> method is
   * called.
   * <p>
   * A subclass of <code>Applet</code> should override this method if
   * it has initialization to perform. For example, an applet with
   * threads would use the <code>init</code> method to create the
   * threads and the <code>destroy</code> method to kill them.
   * <p>
   * The implementation of this method provided by the
   * <code>Applet</code> class does nothing.
   *
   * @see     java.applet.Applet#destroy()
   * @see     java.applet.Applet#start()
   * @see     java.applet.Applet#stop()
   *
   */
  public void init() {
    super.init();
    setContentPane(new SimpleExamplePane());
//    InfiniteTableLayout itl = new InfiniteTableLayout(50, 50, pane);
//    pane.setCustomizerLayout(itl);
//    JCustomizer simpleCustomizer = new JCustomizer(new JLabel("A Simple Component"));
//    pane.addCustomizer(simpleCustomizer, new AbsoluteTableConstraints(0, 0, 150, 50, simpleCustomizer, itl));
  }
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
