/*
 * ControlPanel.java
 *
 * Created on 2. Januar 2008, 19:36
 */
package org.softsmithy.vep;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JColorChooser;
import org.openide.util.Lookup;
import org.openide.util.lookup.Lookups;
import org.softsmithy.lib.swing.action.IconType;
import org.softsmithy.lib.swing.action.XActions;

/**
 *
 * @author  puce
 */
public class ControlPanel extends javax.swing.JPanel {

    private Animation animation;
    private final VisualFieldPane visualFieldPane;
    private Color disabledColor = Color.BLACK;

    /** Creates new form ControlPanel */
    public ControlPanel() {
        initComponents();
        visualFieldPane = VisualFieldViewTopComponent.findInstance().getVisualField();
        visualFieldPane.setVisualFieldAnimationMode((AnimationMode) visualFieldTestBox.getSelectedItem());
        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
        primaryColorLabel.setBackground(visualFieldPane.getPrimaryColor());
        secondaryColorLabel.setBackground(visualFieldPane.getSecondaryColor());
        deviderColorLabel.setBackground(visualFieldPane.getDeviderColor());
        fixationColorLabel.setBackground(visualFieldPane.getFixationColor());
        backgroundColorLabel.setBackground(visualFieldPane.getBackground());
        disabledColorLabel.setBackground(disabledColor);
        Lookup lookup = Lookups.forPath("Actions/VisualField");
        javax.swing.Action action = lookup.lookup(StartAnimationAction.class);
        XActions.configureButton(startButton, lookup.lookup(StartAnimationAction.class), IconType.LARGE_ICON, false, false);
        XActions.configureButton(stopButton, lookup.lookup(StopAnimationAction.class), IconType.LARGE_ICON, false, false);
        //setPreferredSize(new java.awt.Dimension(200, 300));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visualFieldTestBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frequencyBox = new javax.swing.JComboBox();
        primaryColorButton = new javax.swing.JButton();
        primaryColorLabel = new javax.swing.JLabel();
        primaryColorCaptionLabel = new javax.swing.JLabel();
        secondaryColorCaptionLabel = new javax.swing.JLabel();
        secondaryColorLabel = new javax.swing.JLabel();
        secondaryColorButton = new javax.swing.JButton();
        deviderColorButton = new javax.swing.JButton();
        deviderColorLabel = new javax.swing.JLabel();
        deviderColorCaptionLabel = new javax.swing.JLabel();
        fixationColorCaptionLabel = new javax.swing.JLabel();
        fixationColorLabel = new javax.swing.JLabel();
        fixationColorButton = new javax.swing.JButton();
        backgroundColorButton = new javax.swing.JButton();
        backgroundColorLabel = new javax.swing.JLabel();
        backgroundColorCaptionLabel = new javax.swing.JLabel();
        disabledColorCaptionLabel = new javax.swing.JLabel();
        disabledColorLabel = new javax.swing.JLabel();
        disabledColorButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        showVisualFieldCheckBox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(200, 300));

        visualFieldTestBox.setModel(new javax.swing.DefaultComboBoxModel(AnimationMode.values()));
        visualFieldTestBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualFieldTestBoxActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.jLabel2.text")); // NOI18N

        frequencyBox.setModel(new javax.swing.DefaultComboBoxModel(new Integer[]{2, 4, 8, 16}));
        frequencyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyBoxActionPerformed(evt);
            }
        });

        primaryColorButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.primaryColorButton.text")); // NOI18N
        primaryColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primaryColorButtonActionPerformed(evt);
            }
        });

        primaryColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        primaryColorLabel.setOpaque(true);

        primaryColorCaptionLabel.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.primaryColorCaptionLabel.text")); // NOI18N

        secondaryColorCaptionLabel.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.secondaryColorCaptionLabel.text")); // NOI18N

        secondaryColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        secondaryColorLabel.setOpaque(true);

        secondaryColorButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.secondaryColorButton.text")); // NOI18N
        secondaryColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondaryColorButtonActionPerformed(evt);
            }
        });

        deviderColorButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.deviderColorButton.text")); // NOI18N
        deviderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviderColorButtonActionPerformed(evt);
            }
        });

        deviderColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deviderColorLabel.setOpaque(true);

        deviderColorCaptionLabel.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.deviderColorCaptionLabel.text")); // NOI18N

        fixationColorCaptionLabel.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.fixationColorCaptionLabel.text")); // NOI18N

        fixationColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fixationColorLabel.setOpaque(true);

        fixationColorButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.fixationColorButton.text")); // NOI18N
        fixationColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixationColorButtonActionPerformed(evt);
            }
        });

        backgroundColorButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.backgroundColorButton.text")); // NOI18N
        backgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundColorButtonActionPerformed(evt);
            }
        });

        backgroundColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backgroundColorLabel.setOpaque(true);

        backgroundColorCaptionLabel.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.backgroundColorCaptionLabel.text")); // NOI18N

        disabledColorCaptionLabel.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.disabledColorCaptionLabel.text")); // NOI18N

        disabledColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        disabledColorLabel.setOpaque(true);

        disabledColorButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.disabledColorButton.text")); // NOI18N
        disabledColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabledColorButtonActionPerformed(evt);
            }
        });

        stopButton.setEnabled(false);

        showVisualFieldCheckBox.setSelected(true);
        showVisualFieldCheckBox.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.showVisualFieldCheckBox.text")); // NOI18N
        showVisualFieldCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showVisualFieldCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        showVisualFieldCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showVisualFieldCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showVisualFieldCheckBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(disabledColorCaptionLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(primaryColorCaptionLabel)
                                .addComponent(deviderColorCaptionLabel)
                                .addComponent(fixationColorCaptionLabel)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(secondaryColorCaptionLabel))))
                        .addComponent(backgroundColorCaptionLabel))
                    .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showVisualFieldCheckBox))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secondaryColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondaryColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(primaryColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(primaryColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deviderColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deviderColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(disabledColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixationColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backgroundColorButton)
                            .addComponent(fixationColorButton)
                            .addComponent(disabledColorButton)))
                    .addComponent(visualFieldTestBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frequencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(visualFieldTestBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(frequencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaryColorCaptionLabel)
                    .addComponent(primaryColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primaryColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondaryColorCaptionLabel)
                    .addComponent(secondaryColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondaryColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviderColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviderColorCaptionLabel)
                    .addComponent(deviderColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixationColorButton)
                    .addComponent(fixationColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixationColorCaptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundColorButton)
                    .addComponent(backgroundColorCaptionLabel)
                    .addComponent(backgroundColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disabledColorButton)
                    .addComponent(disabledColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disabledColorCaptionLabel))
                .addGap(20, 20, 20)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(showVisualFieldCheckBox)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void visualFieldTestBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualFieldTestBoxActionPerformed
        visualFieldPane.setVisualFieldAnimationMode((AnimationMode) visualFieldTestBox.getSelectedItem());
    }//GEN-LAST:event_visualFieldTestBoxActionPerformed

    private void frequencyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyBoxActionPerformed
        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
    }//GEN-LAST:event_frequencyBoxActionPerformed

    private void primaryColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primaryColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getPrimaryColor());
        if (color != null) {
            primaryColorLabel.setBackground(color);
            visualFieldPane.setPrimaryColor(color);
        }
    }//GEN-LAST:event_primaryColorButtonActionPerformed

    private void secondaryColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondaryColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getSecondaryColor());
        if (color != null) {
            secondaryColorLabel.setBackground(color);
            visualFieldPane.setSecondaryColor(color);
        }
    }//GEN-LAST:event_secondaryColorButtonActionPerformed

    private void deviderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviderColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getDeviderColor());
        if (color != null) {
            deviderColorLabel.setBackground(color);
            visualFieldPane.setDeviderColor(color);
        }
    }//GEN-LAST:event_deviderColorButtonActionPerformed

    private void fixationColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixationColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getFixationColor());
        if (color != null) {
            fixationColorLabel.setBackground(color);
            visualFieldPane.setFixationColor(color);
        }
    }//GEN-LAST:event_fixationColorButtonActionPerformed

    private void backgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getBackground());
        if (color != null) {
            backgroundColorLabel.setBackground(color);
            visualFieldPane.setBackground(color);
        }
    }//GEN-LAST:event_backgroundColorButtonActionPerformed

    private void disabledColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabledColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getDisabledColor());
        if (color != null) {
            disabledColorLabel.setBackground(color);
            visualFieldPane.setDisabledColor(color);
        }
    }//GEN-LAST:event_disabledColorButtonActionPerformed

    private void showVisualFieldCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showVisualFieldCheckBoxItemStateChanged
        visualFieldPane.setVisualFieldDisplayed(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_showVisualFieldCheckBoxItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backgroundColorButton;
    private javax.swing.JLabel backgroundColorCaptionLabel;
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.JButton deviderColorButton;
    private javax.swing.JLabel deviderColorCaptionLabel;
    private javax.swing.JLabel deviderColorLabel;
    private javax.swing.JButton disabledColorButton;
    private javax.swing.JLabel disabledColorCaptionLabel;
    private javax.swing.JLabel disabledColorLabel;
    private javax.swing.JButton fixationColorButton;
    private javax.swing.JLabel fixationColorCaptionLabel;
    private javax.swing.JLabel fixationColorLabel;
    private javax.swing.JComboBox frequencyBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton primaryColorButton;
    private javax.swing.JLabel primaryColorCaptionLabel;
    private javax.swing.JLabel primaryColorLabel;
    private javax.swing.JButton secondaryColorButton;
    private javax.swing.JLabel secondaryColorCaptionLabel;
    private javax.swing.JLabel secondaryColorLabel;
    private javax.swing.JCheckBox showVisualFieldCheckBox;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox visualFieldTestBox;
    // End of variables declaration//GEN-END:variables
    public Animation getAnimation() {
        return animation;
    }
}
