
/*
 * VepFrame2.java
 *
 * Created on 18. Juni 2006, 23:23
 */

package org.softsmithy.vep;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.util.Locale;
import javax.swing.JColorChooser;
import org.softsmithy.lib.swing.action.IconType;
import org.softsmithy.lib.swing.action.MediaActionFactory;
import org.softsmithy.lib.swing.action.XAction;
import org.softsmithy.lib.swing.action.XActions;

/**
 *
 * @author  florian.brunner
 */
public class VepFrame extends javax.swing.JFrame {
    
    private final  VisualFieldPane visualFieldPane;
    private Color disabledColor = Color.BLACK;
    
    /** Creates new form VepFrame2 */
    public VepFrame() {
        initComponents();
        visualFieldPane = new VisualFieldPane();
        try {
            XAction start = MediaActionFactory.PLAY.createXAction(this, Locale.getDefault());
            start.setShortDescription("Start");
            XActions.configureButton(startButton, start, IconType.LARGE_ICON, false, false);
            XAction stop = MediaActionFactory.STOP.createXAction(this, Locale.getDefault());
            stop.setEnabled(false);
            XActions.configureButton(stopButton, stop, IconType.LARGE_ICON, false, false);
        } catch (NoSuchMethodException ex) {
            ex.printStackTrace();
        }
        jSplitPane1.setLeftComponent(visualFieldPane);
        visualFieldPane.setVisualFieldTest((VisualFieldTest) visualFieldTestBox.getSelectedItem());
        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
        primaryColorLabel.setBackground(visualFieldPane.getPrimaryColor());
        secondaryColorLabel.setBackground(visualFieldPane.getSecondaryColor());
        deviderColorLabel.setBackground(visualFieldPane.getDeviderColor());
        fixationColorLabel.setBackground(visualFieldPane.getFixationColor());
        backgroundColorLabel.setBackground(visualFieldPane.getBackground());
        disabledColorLabel.setBackground(disabledColor);
    }
    
    public void mediaPlay(ActionEvent e){
        visualFieldPane.start();
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
    }
    
    public void mediaStop(ActionEvent e){
        visualFieldPane.stop();
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        visualFieldTestBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        frequencyBox = new javax.swing.JComboBox();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        primaryColorCaptionLabel = new javax.swing.JLabel();
        secondaryColorCaptionLabel = new javax.swing.JLabel();
        primaryColorLabel = new javax.swing.JLabel();
        secondaryColorLabel = new javax.swing.JLabel();
        primaryColorButton = new javax.swing.JButton();
        secondaryColorButton = new javax.swing.JButton();
        deviderColorButton = new javax.swing.JButton();
        deviderColorLabel = new javax.swing.JLabel();
        deviderColorCaptionLabel = new javax.swing.JLabel();
        fixationColorButton = new javax.swing.JButton();
        fixationColorLabel = new javax.swing.JLabel();
        fixationColorCaptionLabel = new javax.swing.JLabel();
        backgroundColorCaptionLabel = new javax.swing.JLabel();
        backgroundColorButton = new javax.swing.JButton();
        backgroundColorLabel = new javax.swing.JLabel();
        disabledColorCaptionLabel = new javax.swing.JLabel();
        disabledColorLabel = new javax.swing.JLabel();
        disabledColorButton = new javax.swing.JButton();
        showVisualFieldCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visually Evoked Potentials");
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setOneTouchExpandable(true);
        jLabel1.setLabelFor(visualFieldTestBox);
        jLabel1.setText("Visual Field Test: ");

        visualFieldTestBox.setModel(new javax.swing.DefaultComboBoxModel(VisualFieldTest.values()));
        visualFieldTestBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualFieldTestBoxActionPerformed(evt);
            }
        });

        jLabel2.setLabelFor(frequencyBox);
        jLabel2.setText("Frequency [Hz]: ");

        frequencyBox.setModel(new javax.swing.DefaultComboBoxModel(new Integer[]{2, 4, 8, 16}));
        frequencyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyBoxActionPerformed(evt);
            }
        });

        stopButton.setEnabled(false);

        primaryColorCaptionLabel.setLabelFor(primaryColorLabel);
        primaryColorCaptionLabel.setText("Primary Color: ");

        secondaryColorCaptionLabel.setLabelFor(secondaryColorLabel);
        secondaryColorCaptionLabel.setText("Secondary Color: ");

        primaryColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        primaryColorLabel.setOpaque(true);

        secondaryColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        secondaryColorLabel.setOpaque(true);

        primaryColorButton.setText("...");
        primaryColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primaryColorButtonActionPerformed(evt);
            }
        });

        secondaryColorButton.setText("...");
        secondaryColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondaryColorButtonActionPerformed(evt);
            }
        });

        deviderColorButton.setText("...");
        deviderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviderColorButtonActionPerformed(evt);
            }
        });

        deviderColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deviderColorLabel.setOpaque(true);

        deviderColorCaptionLabel.setLabelFor(deviderColorLabel);
        deviderColorCaptionLabel.setText("Devider Color: ");

        fixationColorButton.setText("...");
        fixationColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixationColorButtonActionPerformed(evt);
            }
        });

        fixationColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fixationColorLabel.setOpaque(true);

        fixationColorCaptionLabel.setLabelFor(fixationColorLabel);
        fixationColorCaptionLabel.setText("Fixation Color: ");

        backgroundColorCaptionLabel.setLabelFor(backgroundColorLabel);
        backgroundColorCaptionLabel.setText("Background Color: ");

        backgroundColorButton.setText("...");
        backgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundColorButtonActionPerformed(evt);
            }
        });

        backgroundColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backgroundColorLabel.setOpaque(true);

        disabledColorCaptionLabel.setLabelFor(fixationColorLabel);
        disabledColorCaptionLabel.setText("Disabled Color: ");

        disabledColorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        disabledColorLabel.setOpaque(true);

        disabledColorButton.setText("...");
        disabledColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabledColorButtonActionPerformed(evt);
            }
        });

        showVisualFieldCheckBox.setSelected(true);
        showVisualFieldCheckBox.setText("Show Visual Field:");
        showVisualFieldCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showVisualFieldCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        showVisualFieldCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showVisualFieldCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showVisualFieldCheckBoxItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(disabledColorCaptionLabel)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(11, 11, 11)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(primaryColorCaptionLabel)
                                .add(deviderColorCaptionLabel)
                                .add(fixationColorCaptionLabel)
                                .add(jLabel2)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(secondaryColorCaptionLabel))))
                        .add(backgroundColorCaptionLabel))
                    .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(showVisualFieldCheckBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(secondaryColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(secondaryColorButton))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(primaryColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(primaryColorButton))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(deviderColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(deviderColorButton))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(disabledColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(backgroundColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(fixationColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(backgroundColorButton)
                                    .add(fixationColorButton)
                                    .add(disabledColorButton)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(visualFieldTestBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(frequencyBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(visualFieldTestBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(frequencyBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(primaryColorCaptionLabel)
                    .add(primaryColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(primaryColorButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(secondaryColorCaptionLabel)
                    .add(secondaryColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(secondaryColorButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(deviderColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(deviderColorCaptionLabel)
                    .add(deviderColorButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fixationColorButton)
                    .add(fixationColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fixationColorCaptionLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backgroundColorButton)
                    .add(backgroundColorCaptionLabel)
                    .add(backgroundColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(disabledColorButton)
                    .add(disabledColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(disabledColorCaptionLabel))
                .add(20, 20, 20)
                .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(showVisualFieldCheckBox)
                .add(52, 52, 52))
        );
        jSplitPane1.setRightComponent(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void showVisualFieldCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showVisualFieldCheckBoxItemStateChanged
        visualFieldPane.setVisualFieldDisplayed(evt.getStateChange() == ItemEvent.SELECTED);
    }//GEN-LAST:event_showVisualFieldCheckBoxItemStateChanged
    
    private void disabledColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabledColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getDisabledColor());
        if (color != null){
            disabledColorLabel.setBackground(color);
            visualFieldPane.setDisabledColor(color);
        }
    }//GEN-LAST:event_disabledColorButtonActionPerformed
    
    private void backgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getBackground());
        if (color != null){
            backgroundColorLabel.setBackground(color);
            visualFieldPane.setBackground(color);
        }
    }//GEN-LAST:event_backgroundColorButtonActionPerformed
    
    private void fixationColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixationColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getFixationColor());
        if (color != null){
            fixationColorLabel.setBackground(color);
            visualFieldPane.setFixationColor(color);
        }
    }//GEN-LAST:event_fixationColorButtonActionPerformed
    
    private void deviderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviderColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getDeviderColor());
        if (color != null){
            deviderColorLabel.setBackground(color);
            visualFieldPane.setDeviderColor(color);
        }
    }//GEN-LAST:event_deviderColorButtonActionPerformed
    
    private void secondaryColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondaryColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getSecondaryColor());
        if (color != null){
            secondaryColorLabel.setBackground(color);
            visualFieldPane.setSecondaryColor(color);
        }
    }//GEN-LAST:event_secondaryColorButtonActionPerformed
    
    private void primaryColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primaryColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose a color...", visualFieldPane.getPrimaryColor());
        if (color != null){
            primaryColorLabel.setBackground(color);
            visualFieldPane.setPrimaryColor(color);
        }
    }//GEN-LAST:event_primaryColorButtonActionPerformed
    
    private void frequencyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyBoxActionPerformed
        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
    }//GEN-LAST:event_frequencyBoxActionPerformed
    
    private void visualFieldTestBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualFieldTestBoxActionPerformed
        visualFieldPane.setVisualFieldTest((VisualFieldTest) visualFieldTestBox.getSelectedItem());
    }//GEN-LAST:event_visualFieldTestBoxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VepFrame().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backgroundColorButton;
    private javax.swing.JLabel backgroundColorCaptionLabel;
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.JButton deviderColorButton;
    private javax.swing.JLabel deviderColorCaptionLabel;
    private javax.swing.JLabel deviderColorLabel;
    private javax.swing.JButton disabledColorButton;
    private javax.swing.JLabel disabledColorCaptionLabel;
    private javax.swing.JLabel disabledColorLabel;
    private javax.swing.JButton fixationColorButton;
    private javax.swing.JLabel fixationColorCaptionLabel;
    private javax.swing.JLabel fixationColorLabel;
    private javax.swing.JComboBox frequencyBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton primaryColorButton;
    private javax.swing.JLabel primaryColorCaptionLabel;
    private javax.swing.JLabel primaryColorLabel;
    private javax.swing.JButton secondaryColorButton;
    private javax.swing.JLabel secondaryColorCaptionLabel;
    private javax.swing.JLabel secondaryColorLabel;
    private javax.swing.JCheckBox showVisualFieldCheckBox;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox visualFieldTestBox;
    // End of variables declaration//GEN-END:variables
    
}
