
/*
 * VepFrame2.java
 *
 * Created on 18. Juni 2006, 23:23
 */

package org.softsmithy.vep;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.util.Locale;
import javax.swing.JColorChooser;
import org.softsmithy.lib.swing.action.IconType;
import org.softsmithy.lib.swing.action.MediaActionFactory;
import org.softsmithy.lib.swing.action.XAction;
import org.softsmithy.lib.swing.action.XActions;

/**
 *
 * @author  florian.brunner
 */
public class VepFrame extends javax.swing.JFrame {
    
    private final  VisualFieldPane visualFieldPane;
    private Color disabledColor = Color.BLACK;
    
    /** Creates new form VepFrame2 */
    public VepFrame() {
        initComponents();
        visualFieldPane = new VisualFieldPane();
//        try {
//            XAction start = MediaActionFactory.PLAY.createXAction(this, Locale.getDefault());
//            start.setShortDescription("Start");
//            XActions.configureButton(startButton, start, IconType.LARGE_ICON, false, false);
//            XAction stop = MediaActionFactory.STOP.createXAction(this, Locale.getDefault());
//            stop.setEnabled(false);
//            XActions.configureButton(stopButton, stop, IconType.LARGE_ICON, false, false);
//        } catch (NoSuchMethodException ex) {
//            ex.printStackTrace();
//        }
//        jSplitPane1.setLeftComponent(visualFieldPane);
//        visualFieldPane.setVisualFieldAnimationMode((AnimationMode) visualFieldTestBox.getSelectedItem());
//        visualFieldPane.setFrequency((Integer) frequencyBox.getSelectedItem());
//        primaryColorLabel.setBackground(visualFieldPane.getPrimaryColor());
//        secondaryColorLabel.setBackground(visualFieldPane.getSecondaryColor());
//        deviderColorLabel.setBackground(visualFieldPane.getDeviderColor());
//        fixationColorLabel.setBackground(visualFieldPane.getFixationColor());
//        backgroundColorLabel.setBackground(visualFieldPane.getBackground());
//        disabledColorLabel.setBackground(disabledColor);
    }
    
    public void mediaPlay(ActionEvent e){
        visualFieldPane.start();
//        startButton.setEnabled(false);
//        stopButton.setEnabled(true);
    }
    
    public void mediaStop(ActionEvent e){
        visualFieldPane.stop();
//        startButton.setEnabled(true);
//        stopButton.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visually Evoked Potentials");

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setOneTouchExpandable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VepFrame().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
}
