/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.softsmithy.vep;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.logging.Logger;
import org.openide.util.NbBundle;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;
/**
 * Top component which displays something.
 */
final class VisualFieldViewTopComponent extends TopComponent {

    private static VisualFieldViewTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "VisualFieldViewTopComponent";
    private final VisualFieldPane visualFieldPane = new VisualFieldPane();
    private final InstanceContent content = new InstanceContent();
    private final StartAnimation startAnimationSupport;
    private final StopAnimation stopAnimationSupport;

    private VisualFieldViewTopComponent() {
        initComponents();
        add(visualFieldPane, BorderLayout.CENTER);
        setName(NbBundle.getMessage(VisualFieldViewTopComponent.class, "CTL_VisualFieldViewTopComponent"));
        setToolTipText(NbBundle.getMessage(VisualFieldViewTopComponent.class, "HINT_VisualFieldViewTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
        associateLookup(new AbstractLookup(content));
        startAnimationSupport = new StartAnimation() {

            public void startAnimation() {
                synchronized (VisualFieldViewTopComponent.this) { // TODO: synchronize on lookup?
                    getVisualField().start();
                    content.remove(startAnimationSupport);
                    content.add(stopAnimationSupport);
                }
            }
        };

        stopAnimationSupport = new StopAnimation() {

            public void stopAnimation() {
                synchronized (VisualFieldViewTopComponent.this) { // TODO: synchronize on lookup?
                    getVisualField().stop();
                    content.remove(stopAnimationSupport);
                    content.add(startAnimationSupport);
                }
            }

        };
        content.add(startAnimationSupport);
    }

    public VisualFieldPane getVisualField() {
        return visualFieldPane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized VisualFieldViewTopComponent getDefault() {
        if (instance == null) {
            instance = new VisualFieldViewTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the VisualFieldViewTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized VisualFieldViewTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(VisualFieldViewTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof VisualFieldViewTopComponent) {
            return (VisualFieldViewTopComponent) win;
        }
        Logger.getLogger(VisualFieldViewTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
    // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
    // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return VisualFieldViewTopComponent.getDefault();
        }
    }
}
